CONTIKI = ../../..
CONTIKI_PROJECT = example-broadcast example-PA

MAKE_MAC = MAKE_MAC_NULLMAC
MAKE_NET = MAKE_NET_NULLNET

MODULES_REL += dev/ca-tag
MODULES_REL += net/mac/nullmac

all: $(CONTIKI_PROJECT)
include $(CONTIKI)/Makefile.include
